language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
  - eval "$(gimme 1.13)"
  - yarn run prereq:router
script:
  - yarn run build:clean
  - yarn run test:fast
  - yarn run codecov
go:
  - "1.13.x"
node_js:
  - "10.13"
